---
engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false  # matches in different files
    config:
      languages:
        - c
        - java
  fixme:
    enabled: true
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
ratings:
  paths:
    - "**.js"
    - "**.cpp"
    - "**.c"
    - "**.py"
exclude_paths: []
